//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class cv
    {
        public int id_cv { get; set; }
        public string cod_cv { get; set; }
    }
}
