//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class angajator
    {
        public int id_angajator { get; set; }
        public string email { get; set; }
        public string parola { get; set; }
        public string nume_angajator { get; set; }
        public string telefon { get; set; }
        public bool verificare_email { get; set; }
        public Nullable<System.Guid> cod_activare { get; set; }
        public string nr_ordine_registru_comert { get; set; }
        public string oras_sediu { get; set; }
        public string tara_sediu { get; set; }
        public string adresa_sediu { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string cod_resetare_parola { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
