//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicare_job
    {
        public int id_aplicare { get; set; }
        public string cod_job { get; set; }
        public string angajator { get; set; }
        public string email_angajat { get; set; }
        public Nullable<System.DateTime> data_aplicare { get; set; }
        public string nume_angajat { get; set; }
        public Nullable<byte> aplicat { get; set; }
    }
}
