//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.

//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    // grija la autoregenerare => stergere
    public partial class DBrecrutare : DbContext
    {
        public DBrecrutare()
            : base("name=DBrecrutare")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<utilizator_domeniu_leg>()
           .HasKey(t => new { t.id_domeniu, t.id_utilizator });

            modelBuilder.Entity<utilizator_domeniu_leg>()
                .HasOptional(ud => ud.domeniu_lucru)
                .WithMany(p => p.utilizator_domeniu_leg)
                .HasForeignKey(ud => ud.id_domeniu);

            modelBuilder.Entity<utilizator_domeniu_leg>()
                .HasOptional(ud => ud.utilizator)
                .WithMany(t => t.utilizator_domeniu_leg)
                .HasForeignKey(ud => ud.id_utilizator);

           // throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<cv> cvs { get; set; }
        public virtual DbSet<domeniu_lucru> domeniu_lucru { get; set; }
        public virtual DbSet<utilizator> utilizators { get; set; }
        public virtual DbSet<utilizator_domeniu_leg> utilizator_domeniu_leg { get; set; }
    }
}
