//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBrecrutare : DbContext
    {
        public DBrecrutare()
            : base("name=DBrecrutare")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<domeniu_lucru> domeniu_lucru { get; set; }
        public virtual DbSet<utilizator> utilizators { get; set; }
        public virtual DbSet<utilizator_domeniu_leg> utilizator_domeniu_leg { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<angajator> angajators { get; set; }
        public virtual DbSet<cv> cvs { get; set; }
        public virtual DbSet<aplicare_job> aplicare_job { get; set; }
    }
}
