//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class domeniu_lucru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public domeniu_lucru()
        {
            this.utilizator_domeniu_leg = new HashSet<utilizator_domeniu_leg>();
        }
    
        public int id_domeniu { get; set; }
        public string denumire_domeniu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilizator_domeniu_leg> utilizator_domeniu_leg { get; set; }
        //public IList<utilizator_domeniu_leg> utilizator_domeniu_leg { get; set; }
    }
}
