//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id_job { get; set; }
        public string denumire_job { get; set; }
        public string cod_job { get; set; }
        public Nullable<System.DateTime> data_expirare_job { get; set; }
        public string angajator { get; set; }
        public byte[] imagine_job { get; set; }
        public string descriere_job { get; set; }
        public Nullable<System.DateTime> data_creare_job { get; set; }
        public string tara { get; set; }
        public string oras { get; set; }
        public string norma_job { get; set; }
    }
}
