//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilizator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utilizator()
        {
            this.utilizator_domeniu_leg = new HashSet<utilizator_domeniu_leg>();
        }
    
        public string email { get; set; }
        public string parola { get; set; }
        public string nume_utilizator { get; set; }
        public string prenume_utilizator { get; set; }
        public string oras { get; set; }
        public string telefon { get; set; }
        public Nullable<System.DateTime> data_nasterii { get; set; }
        public string sex { get; set; }
        public bool verificare_email { get; set; }
        public Nullable<System.Guid> cod_activare { get; set; }
        public int id_utilizator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilizator_domeniu_leg> utilizator_domeniu_leg { get; set; }
    }
}
