//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemRecrutare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilizator_domeniu_leg
    {
        public int id_utilizator { get; set; }
        public int id_domeniu { get; set; }
        public string camp { get; set; }
    
        public virtual domeniu_lucru domeniu_lucru { get; set; }
        public virtual utilizator utilizator { get; set; }
    }
}
